### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by PuRonglong** [jiacai2050/better-history#13]
=_=

**Comment by jiacai2050** [comment]
你好吓人，这个你都知道。多方面原因吧，暂时不想离开杭州。

**Comment by PuRonglong** [comment]
→_→
其实我是猎头，嘘，不要告诉别人😂
如果不想离开杭州，那当初就不会投杭州以外的吧，我猜是同事让你留下了😃
微博粉你啦~
我只是一个闲逛的游民，O(∩_∩)O哈哈~

**Comment by PuRonglong** [comment]
总之，加油吧！
