### ISSUE TITLE
有意思的应用，顺便请教

### ISSUE THREAD

**Issue by ivanberry** [jiacai2050/better-history#14]
## 动画自定义？

个人从echart2迁移到echart3的过程中，发现饼图的动画方式默认不同了，你的应用中还是echart2的小到大的展现，而echart3中则仅可以定义顺逆时针，并能定义动画总时间，阈值等。

请问你的动画是自定义的还是echart3有我没找打的配置选项，谢谢

**Comment by jiacai2050** [comment]
我不知道你说的自定义是指什么，echart3 我也没怎么用过，画图的代码在https://github.com/jiacai2050/better-history/blob/master/assets/js/main.js#L85 ，你可以参考。
