### ISSUE TITLE
关于时间范围选择的问题，如图

### ISSUE THREAD

**Issue by PuRonglong** [jiacai2050/better-history#15]
@jiacai2050 
hello~请问为什么时间只能选到9月25号的呢，想要选2016全年的怎么办呢？

![image](https://cloud.githubusercontent.com/assets/8725006/21466092/7c8c60c4-c9f7-11e6-8e20-a721681ec83d.png)

**Comment by jiacai2050** [comment]
这是因为你的浏览记录只保留到9月25号的，之前的数据没了。你可以用 浏览器自带的历史纪录看下

**Comment by PuRonglong** [comment]
查了下，浏览器的记录chrome最多保存3个月的。貌似没有办法获取更多的数据了。 不过查看的话倒是可以，基于某个账户，google可以查看更长时间的记录：https://myactivity.google.com/myactivity
