### ISSUE TITLE
How can we start the Firefox extension?

### ISSUE THREAD

**Issue by protist** [jiacai2050/better-history#16]
I just installed the Firefox addon, but it's unclear how to start it. Could you please explain where we can launch it? There's nothing in the History or Tools menus, nor any options in the addon page itself.

**Comment by jiacai2050** [comment]
It is inside `Open menu` in Firefox v50.1.0.
![image](https://cloud.githubusercontent.com/assets/3848910/23929170/1f12f2e4-095f-11e7-8ae6-dc9f5c84a142.png)


You can check whether it is installed properly in `about:addons` page

**Comment by protist** [comment]
Ah yes, got it, thank you!
