### ISSUE TITLE
run as server in local network

### ISSUE THREAD

**Issue by gitty8** [jiacai2050/better-history#17]
Possible to use this to install extension on all devices in local network and fetch data to an local better history server on the local network?

**Comment by jiacai2050** [comment]
I have no idea what you want to do. Can you explain it more ?

**Comment by gitty8** [comment]
for example i have 5 clients running this chrome extension and 1 server in local network.
The 5 clients set chrome extension "better history" to point to 1 server in local network. The server in local network fetches everything and shows by clients the history.
Is this possible?

**Comment by jiacai2050** [comment]
Got it.

But I don't think you can do it like what you said. Every Chrome profile has one and only one history file, and this addon will read that single history file to analyze.

But if you can merge those history files then you can do it. you can dig more into [this question](https://superuser.com/questions/613469/how-can-i-transfer-google-chromes-data-and-settings-to-another-google-account) on superuser.
