### ISSUE TITLE
Stats for security

### ISSUE THREAD

**Issue by Madis0** [jiacai2050/better-history#18]
Hello,
I've tried this extension out and it does indeed give me a better impression of my browsing history.

I got an idea though - what if it also displayed the security of the sites' connection?

- A separate chart showing the amount of sites visited with HTTP vs HTTPS protocol
- A column for Visits Rank TOP 100 items showing normal/broken lock icon by the protocol 

That would help the users know how private their histories and web actions are or even benchmark the usefulness of extensions like HTTPS Everywhere and Smart HTTPS.

What do you think?

**Comment by jiacai2050** [comment]
Sorry for the delay.

Security stats is little interest to me, so...

If you like, PRs are welcomed.

**Comment by jiacai2050** [comment]
This feature is added after 2.0.0

**Comment by Madis0** [comment]
Ooh, nice graph! 😁
