### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [jiacai2050/better-history#19]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by jiacai2050** [comment]
Thanks @Drulac for pointing out template-literal, I haven't heard it before.

However, this project is migrated to clojurescript, which compile clojure to JS, the extension version have been ported, you can try it now. 
I will migrate the node version later, although no plan made. If you like, PR are welcomed.
