### ISSUE TITLE
执行时的报错问题

### ISSUE THREAD

**Issue by PuRonglong** [jiacai2050/better-history#2]
你好，请教下跑的时候报如下错
![snip20160114_1](https://cloud.githubusercontent.com/assets/8725006/12318198/7c88ee00-bad3-11e5-963c-5b8611dd75b7.png)
node 版本0.12

**Comment by lizy14** [comment]
手动将代码中的 ` 改为 ' 或许可以解决问题

**Comment by PuRonglong** [comment]
先前试过手动将`改为'，但是在代码的46行会有错
![snip20160114_4](https://cloud.githubusercontent.com/assets/8725006/12318502/d1d90c1c-bad5-11e5-8114-6e17e33d4a34.png)

无奈将`改为"执行，报错如下
![snip20160114_5](https://cloud.githubusercontent.com/assets/8725006/12318554/1e106012-bad6-11e5-8ae6-9f6889918cec.png)

查看确实为没有这个文件，文件目录如下
![snip20160114_8](https://cloud.githubusercontent.com/assets/8725006/12318630/b85502d6-bad6-11e5-9bf0-f4eda8536e11.png)
所以还是没有跑起来的

**Comment by jiacai2050** [comment]
```
`hello world`
```

这种形式的字符串是 ES6 新增的 [Template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings)，我 Mac 上 node 的版本为`v4.2.1`是默认支持这种语法的，低版本可以试试`node --harmony`，或者干脆升级到最新版。

**Comment by jiacai2050** [comment]
看了下 nodejs 的文档
Template strings 需要在 [v4.0.0](https://nodejs.org/en/blog/release/v4.0.0/) 以上版本才能使用

**Comment by PuRonglong** [comment]
嗯，的确版本问题

5都出来了，是该升下级了😂

升级node后又遇到了一些问题，已解决并提说明

O(∩_∩)O谢谢@jiacai2050
