### ISSUE TITLE
Don't see today's date

### ISSUE THREAD

**Issue by travisfont** [jiacai2050/better-history#20]
How are dates manage?

It's 10:50 am and I don't see any history for this morning (real-time).

**Comment by jiacai2050** [comment]
The default date range doesn't include today's history, I will release another version to solve this.

**Comment by jiacai2050** [comment]
Fixed: https://github.com/jiacai2050/history-master/commit/4c6d20a28ddadc14d504f1f4316fe805f12c5f94
