### ISSUE TITLE
SQLITE_ERROR: no such column

### ISSUE THREAD

**Issue by lizy14** [jiacai2050/better-history#3]
`{ [Error: SQLITE_ERROR: no such column: ] errno: 1, code: 'SQLITE_ERROR' }`

from lib/chrome.js, line 53.

`http://localhost:5210/` 只显示每日浏览量曲线：

![image](https://cloud.githubusercontent.com/assets/9985286/12319224/b9f6df42-badb-11e5-999f-603a8b61c116.png)

Windows 7, Google Chrome `49.0.2618.8 dev-m`.

**Comment by jiacai2050** [comment]
你是不是修改上面的sql来，
https://github.com/jiacai2050/chrome-history-stat/blob/0058fa9c964e8a191c0df1eb8828ad1137b409ab/lib/chrome.js#L37

怎么会出现`]`列的呢？

**Comment by lizy14** [comment]
it's my fault.
please close this issue.
