### ISSUE TITLE
扩展不能正常显示内容了

### ISSUE THREAD

**Issue by MeowSalty** [jiacai2050/better-history#35]
最近发现变成这样子了，而且重装插件也没什么变化，而且在重装扩展的过程中多次下载出错（好像在chrome周年更新之后才这样的）。看了下控制台发现是扩展引用的样式文件和图片都被墙了……
![image](https://user-images.githubusercontent.com/7829265/46286914-7eaec180-c5b3-11e8-8f9e-0d91827c2859.png)

**Comment by jiacai2050** [comment]
Thanks for reporting. Release 2.1.2 fix this.
