### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by jcamp** [jiacai2050/better-history#36]
Is it possible to be able to 'group' by the main domain for a set period?

And then be able to filter on that domain and expand the entries?

Would be really useful :)

Cheers
Jonathan

**Comment by jiacai2050** [comment]
Hi, what do you mean by `group by the main domain`? 
If you want to view all items within a domain (eg. example.com), just search `example.com`, then the results will only be relation to example.com.

**Comment by jiacai2050** [comment]
close for inactive
