### ISSUE TITLE
Import Functionality?

### ISSUE THREAD

**Issue by TheBedouin** [jiacai2050/better-history#42]
Hi there,
I really like the extension, especially the fact that it runs on both FF and Chrome. My question is though: Is there a way to import or "sync" the history for those of us who use both browsers? The export functionality is great, however, its value is diminished if it cannot be used elsewhere, don't you agree?
Thanks a lot and keep up the good work,
The Bedouin

**Comment by jiacai2050** [comment]
Hi, thanks for your suggestion. 
I think this feature is useful for those using multiple browsers(at work/home...) , stay tuned for the next release.

**Comment by jiacai2050** [comment]
Related API: 
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/addUrl
- https://developers.chrome.com/extensions/history#method-addUrl only support add history at current time
