### ISSUE TITLE
未安装firefox执行会报错

### ISSUE THREAD

**Issue by PuRonglong** [jiacai2050/better-history#9]
未安装firefox执行会报错

**Comment by jiacai2050** [comment]
已经修复
https://github.com/jiacai2050/chrome-history-stat/commit/ce85c38a63f5edf7e548e62fb9d7a7bdb83b2517

**Comment by PuRonglong** [comment]
@jiacai2050 
执行时还是报错，如下

![snip20160117_16](https://cloud.githubusercontent.com/assets/8725006/12375616/89700c64-bd05-11e5-9963-ce72a36ffc52.png)

**Comment by jiacai2050** [comment]
这明显是端口占用的错误，你是不是开启了两次

**Comment by PuRonglong** [comment]
sorry，我的，可以了
👍
